// Generated by Scripts/generate-bindings.py. Do not edit directly.
// Adapted from simdutf, available under MIT or Apache-2.0.
// See simdutf/LICENSE-MIT and simdutf/LICENSE-APACHE.
import CSimdUTF

// C result types are values; buffers stay borrowed for the duration of each call.
public typealias simdutf_error_code = CSimdUTF.simdutf_error_code
public typealias simdutf_result = CSimdUTF.simdutf_result
public typealias simdutf_full_result = CSimdUTF.simdutf_full_result
public let SIMDUTF_ERROR_SUCCESS = CSimdUTF.SIMDUTF_ERROR_SUCCESS
public let SIMDUTF_ERROR_HEADER_BITS = CSimdUTF.SIMDUTF_ERROR_HEADER_BITS
public let SIMDUTF_ERROR_TOO_SHORT = CSimdUTF.SIMDUTF_ERROR_TOO_SHORT
public let SIMDUTF_ERROR_TOO_LONG = CSimdUTF.SIMDUTF_ERROR_TOO_LONG
public let SIMDUTF_ERROR_OVERLONG = CSimdUTF.SIMDUTF_ERROR_OVERLONG
public let SIMDUTF_ERROR_TOO_LARGE = CSimdUTF.SIMDUTF_ERROR_TOO_LARGE
public let SIMDUTF_ERROR_SURROGATE = CSimdUTF.SIMDUTF_ERROR_SURROGATE
public let SIMDUTF_ERROR_INVALID_BASE64_CHARACTER = CSimdUTF.SIMDUTF_ERROR_INVALID_BASE64_CHARACTER
public let SIMDUTF_ERROR_BASE64_INPUT_REMAINDER = CSimdUTF.SIMDUTF_ERROR_BASE64_INPUT_REMAINDER
public let SIMDUTF_ERROR_BASE64_EXTRA_BITS = CSimdUTF.SIMDUTF_ERROR_BASE64_EXTRA_BITS
public let SIMDUTF_ERROR_OUTPUT_BUFFER_TOO_SMALL = CSimdUTF.SIMDUTF_ERROR_OUTPUT_BUFFER_TOO_SMALL
public let SIMDUTF_ERROR_OTHER = CSimdUTF.SIMDUTF_ERROR_OTHER

#if DetectEncoding
public typealias simdutf_encoding_type = CSimdUTF.simdutf_encoding_type
public let SIMDUTF_ENCODING_UNSPECIFIED = CSimdUTF.SIMDUTF_ENCODING_UNSPECIFIED
public let SIMDUTF_ENCODING_UTF8 = CSimdUTF.SIMDUTF_ENCODING_UTF8
public let SIMDUTF_ENCODING_UTF16_LE = CSimdUTF.SIMDUTF_ENCODING_UTF16_LE
public let SIMDUTF_ENCODING_UTF16_BE = CSimdUTF.SIMDUTF_ENCODING_UTF16_BE
public let SIMDUTF_ENCODING_UTF32_LE = CSimdUTF.SIMDUTF_ENCODING_UTF32_LE
public let SIMDUTF_ENCODING_UTF32_BE = CSimdUTF.SIMDUTF_ENCODING_UTF32_BE
#endif

#if Base64
public typealias simdutf_base64_options = CSimdUTF.simdutf_base64_options
public typealias simdutf_last_chunk_handling_options = CSimdUTF.simdutf_last_chunk_handling_options
public let SIMDUTF_BASE64_DEFAULT = CSimdUTF.SIMDUTF_BASE64_DEFAULT
public let SIMDUTF_BASE64_URL = CSimdUTF.SIMDUTF_BASE64_URL
public let SIMDUTF_BASE64_DEFAULT_NO_PADDING = CSimdUTF.SIMDUTF_BASE64_DEFAULT_NO_PADDING
public let SIMDUTF_BASE64_URL_WITH_PADDING = CSimdUTF.SIMDUTF_BASE64_URL_WITH_PADDING
public let SIMDUTF_BASE64_DEFAULT_ACCEPT_GARBAGE = CSimdUTF.SIMDUTF_BASE64_DEFAULT_ACCEPT_GARBAGE
public let SIMDUTF_BASE64_URL_ACCEPT_GARBAGE = CSimdUTF.SIMDUTF_BASE64_URL_ACCEPT_GARBAGE
public let SIMDUTF_BASE64_DEFAULT_OR_URL = CSimdUTF.SIMDUTF_BASE64_DEFAULT_OR_URL
public let SIMDUTF_BASE64_DEFAULT_OR_URL_ACCEPT_GARBAGE = CSimdUTF.SIMDUTF_BASE64_DEFAULT_OR_URL_ACCEPT_GARBAGE
public let SIMDUTF_LAST_CHUNK_LOOSE = CSimdUTF.SIMDUTF_LAST_CHUNK_LOOSE
public let SIMDUTF_LAST_CHUNK_STRICT = CSimdUTF.SIMDUTF_LAST_CHUNK_STRICT
public let SIMDUTF_LAST_CHUNK_STOP_BEFORE_PARTIAL = CSimdUTF.SIMDUTF_LAST_CHUNK_STOP_BEFORE_PARTIAL
public let SIMDUTF_LAST_CHUNK_ONLY_FULL_CHUNKS = CSimdUTF.SIMDUTF_LAST_CHUNK_ONLY_FULL_CHUNKS
#endif

// The counted-buffer APIs follow the upstream C API. Counts and capacities
// must be nonnegative. Conversion inputs and
// outputs must not overlap. Supply enough output capacity as documented by
// simdutf; *_safe variants accept explicit output capacity.

#if (UTF8 || DetectEncoding)
@inlinable
@inline(__always)
public func simdutf_validate_utf8(_ buf: UnsafePointer<CChar>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf8(buf, len)
}
#endif

#if (UTF8)
@inlinable
@inline(__always)
public func simdutf_validate_utf8_with_errors(_ buf: UnsafePointer<CChar>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_utf8_with_errors(buf, len)
}
#endif

#if (DetectEncoding)
@inlinable
@inline(__always)
public func simdutf_autodetect_encoding(_ input: UnsafePointer<CChar>?, _ length: Int) -> simdutf_encoding_type {
  CSimdUTF.simdutf_autodetect_encoding(input, length)
}
#endif

#if (DetectEncoding)
@inlinable
@inline(__always)
public func simdutf_detect_encodings(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int32 {
  CSimdUTF.simdutf_detect_encodings(input, length)
}
#endif

#if (ASCII)
@inlinable
@inline(__always)
public func simdutf_validate_ascii(_ buf: UnsafePointer<CChar>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_ascii(buf, len)
}
#endif

#if (ASCII)
@inlinable
@inline(__always)
public func simdutf_validate_ascii_with_errors(_ buf: UnsafePointer<CChar>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_ascii_with_errors(buf, len)
}
#endif

#if (UTF16 && ASCII)
@inlinable
@inline(__always)
public func simdutf_validate_utf16_as_ascii(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16_as_ascii(buf, len)
}
#endif

#if (UTF16 && ASCII)
@inlinable
@inline(__always)
public func simdutf_validate_utf16be_as_ascii(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16be_as_ascii(buf, len)
}
#endif

#if (UTF16 && ASCII)
@inlinable
@inline(__always)
public func simdutf_validate_utf16le_as_ascii(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16le_as_ascii(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_validate_utf16(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16(buf, len)
}
#endif

#if (UTF16 || DetectEncoding)
@inlinable
@inline(__always)
public func simdutf_validate_utf16le(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16le(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_validate_utf16be(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf16be(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_validate_utf16_with_errors(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_utf16_with_errors(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_validate_utf16le_with_errors(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_utf16le_with_errors(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_validate_utf16be_with_errors(_ buf: UnsafePointer<UInt16>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_utf16be_with_errors(buf, len)
}
#endif

#if (UTF32 || DetectEncoding)
@inlinable
@inline(__always)
public func simdutf_validate_utf32(_ buf: UnsafePointer<UInt32>?, _ len: Int) -> Bool {
  CSimdUTF.simdutf_validate_utf32(buf, len)
}
#endif

#if (UTF32)
@inlinable
@inline(__always)
public func simdutf_validate_utf32_with_errors(_ buf: UnsafePointer<UInt32>?, _ len: Int) -> simdutf_result {
  CSimdUTF.simdutf_validate_utf32_with_errors(buf, len)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_to_well_formed_utf16le(_ input: UnsafePointer<UInt16>?, _ len: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Void {
  CSimdUTF.simdutf_to_well_formed_utf16le(input, len, output)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_to_well_formed_utf16be(_ input: UnsafePointer<UInt16>?, _ len: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Void {
  CSimdUTF.simdutf_to_well_formed_utf16be(input, len, output)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_to_well_formed_utf16(_ input: UnsafePointer<UInt16>?, _ len: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Void {
  CSimdUTF.simdutf_to_well_formed_utf16(input, len, output)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_count_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_count_utf16(input, length)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_count_utf16le(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_count_utf16le(input, length)
}
#endif

#if (UTF16)
@inlinable
@inline(__always)
public func simdutf_count_utf16be(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_count_utf16be(input, length)
}
#endif

#if (UTF8)
@inlinable
@inline(__always)
public func simdutf_count_utf8(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_count_utf8(input, length)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_latin1(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf8_length_from_latin1(input, length)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_latin1_length_from_utf8(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_latin1_length_from_utf8(input, length)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_latin1_length_from_utf16(_ length: Int) -> Int {
  CSimdUTF.simdutf_latin1_length_from_utf16(length)
}
#endif

#if (UTF32 && Latin1)
@inlinable
@inline(__always)
public func simdutf_latin1_length_from_utf32(_ length: Int) -> Int {
  CSimdUTF.simdutf_latin1_length_from_utf32(length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf16_length_from_utf8(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf16_length_from_utf8(input, length)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_utf32_length_from_utf8(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf32_length_from_utf8(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf8_length_from_utf16(input, length)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf32(_ input: UnsafePointer<UInt32>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf8_length_from_utf32(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int) -> simdutf_result {
  CSimdUTF.simdutf_utf8_length_from_utf16_with_replacement(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16le(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf8_length_from_utf16le(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16be(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_utf8_length_from_utf16be(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16le_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int) -> simdutf_result {
  CSimdUTF.simdutf_utf8_length_from_utf16le_with_replacement(input, length)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_utf8_length_from_utf16be_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int) -> simdutf_result {
  CSimdUTF.simdutf_utf8_length_from_utf16be_with_replacement(input, length)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf8(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf8(input, length, output)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf8_safe(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ utf8_len: Int) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf8_safe(input, length, output, utf8_len)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf8_safe_with_details(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ utf8_len: Int) -> simdutf_full_result {
  CSimdUTF.simdutf_convert_latin1_to_utf8_safe_with_details(input, length, output, utf8_len)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf16le(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf16le(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf16be(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf16be(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf16(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf16(input, length, output)
}
#endif

#if (UTF32 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_latin1_to_utf32(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_latin1_to_utf32(input, length, output)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_latin1(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf8_to_latin1(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16le(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf8_to_utf16le(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf8_to_utf16(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16be(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf8_to_utf16be(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf32(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_utf8_to_utf32(input, length, output)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_latin1_with_errors(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf8_to_latin1_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16_with_errors(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf8_to_utf16_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16le_with_errors(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf8_to_utf16le_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf16be_with_errors(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf8_to_utf16be_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf8_to_utf32_with_errors(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf8_to_utf32_with_errors(input, length, output)
}
#endif

#if (UTF8 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf8_to_latin1(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf8_to_latin1(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf8_to_utf16le(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf8_to_utf16le(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf8_to_utf16be(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf8_to_utf16be(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf8_to_utf32(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf8_to_utf32(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16_to_utf8(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8_safe(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ utf8_len: Int) -> Int {
  CSimdUTF.simdutf_convert_utf16_to_utf8_safe(input, length, output, utf8_len)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8_safe_with_details(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ utf8_len: Int) -> simdutf_full_result {
  CSimdUTF.simdutf_convert_utf16_to_utf8_safe_with_details(input, length, output, utf8_len)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16_to_latin1(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16le_to_latin1(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16be_to_latin1(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_latin1_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16_to_latin1_with_errors(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_latin1_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16le_to_latin1_with_errors(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_latin1_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16be_to_latin1_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16_to_utf8_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_utf8_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16le_to_utf8_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_utf8_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16be_to_utf8_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16le_to_utf8(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16be_to_utf8(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16_to_utf8_with_replacement(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf8_with_replacement_safe(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ utf8_len: Int) -> simdutf_full_result {
  CSimdUTF.simdutf_convert_utf16_to_utf8_with_replacement_safe(input, length, output, utf8_len)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_utf8_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16le_to_utf8_with_replacement(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_utf8_with_replacement(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf16be_to_utf8_with_replacement(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16_to_utf8(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16_to_latin1(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16le_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16le_to_latin1(input, length, output)
}
#endif

#if (UTF16 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16be_to_latin1(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16be_to_latin1(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16le_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16le_to_utf8(input, length, output)
}
#endif

#if (UTF8 && UTF16)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16be_to_utf8(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16be_to_utf8(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_utf16_to_utf32(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_utf16le_to_utf32(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_utf16be_to_utf32(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16_to_utf32_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16_to_utf32_with_errors(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16le_to_utf32_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16le_to_utf32_with_errors(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf16be_to_utf32_with_errors(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf16be_to_utf32_with_errors(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16_to_utf32(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16le_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16le_to_utf32(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf16be_to_utf32(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<UInt32>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf16be_to_utf32(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_utf8(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_utf32_to_utf8(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_utf8_with_errors(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf32_to_utf8_with_errors(input, length, output)
}
#endif

#if (UTF8 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_valid_utf32_to_utf8(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> Int {
  CSimdUTF.simdutf_convert_valid_utf32_to_utf8(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_utf16(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf32_to_utf16(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_utf16le(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf32_to_utf16le(input, length, output)
}
#endif

#if (UTF16 && UTF32)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_utf16be(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<UInt16>?) -> Int {
  CSimdUTF.simdutf_convert_utf32_to_utf16be(input, length, output)
}
#endif

#if (UTF32 && Latin1)
@inlinable
@inline(__always)
public func simdutf_convert_utf32_to_latin1_with_errors(_ input: UnsafePointer<UInt32>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?) -> simdutf_result {
  CSimdUTF.simdutf_convert_utf32_to_latin1_with_errors(input, length, output)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_find(_ start: UnsafePointer<CChar>?, _ end: UnsafePointer<CChar>?, _ character: CChar) -> UnsafePointer<CChar>? {
  CSimdUTF.simdutf_find(start, end, character)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_find_utf16(_ start: UnsafePointer<UInt16>?, _ end: UnsafePointer<UInt16>?, _ character: UInt16) -> UnsafePointer<UInt16>? {
  CSimdUTF.simdutf_find_utf16(start, end, character)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_maximal_binary_length_from_base64(_ input: UnsafePointer<CChar>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_maximal_binary_length_from_base64(input, length)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_maximal_binary_length_from_base64_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int) -> Int {
  CSimdUTF.simdutf_maximal_binary_length_from_base64_utf16(input, length)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options) -> simdutf_result {
  CSimdUTF.simdutf_base64_to_binary(input, length, output, options, last_chunk_options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options) -> simdutf_result {
  CSimdUTF.simdutf_base64_to_binary_utf16(input, length, output, options, last_chunk_options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_length_from_binary(_ length: Int, _ options: simdutf_base64_options) -> Int {
  CSimdUTF.simdutf_base64_length_from_binary(length, options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_length_from_binary_with_lines(_ length: Int, _ options: simdutf_base64_options, _ line_length: Int) -> Int {
  CSimdUTF.simdutf_base64_length_from_binary_with_lines(length, options, line_length)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_binary_to_base64(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ options: simdutf_base64_options) -> Int {
  CSimdUTF.simdutf_binary_to_base64(input, length, output, options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_binary_to_base64_with_lines(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ line_length: Int, _ options: simdutf_base64_options) -> Int {
  CSimdUTF.simdutf_binary_to_base64_with_lines(input, length, output, line_length, options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary_safe(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ outlen: UnsafeMutablePointer<Int>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options, _ decode_up_to_bad_char: Bool) -> simdutf_result {
  CSimdUTF.simdutf_base64_to_binary_safe(input, length, output, outlen, options, last_chunk_options, decode_up_to_bad_char)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary_safe_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ outlen: UnsafeMutablePointer<Int>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options, _ decode_up_to_bad_char: Bool) -> simdutf_result {
  CSimdUTF.simdutf_base64_to_binary_safe_utf16(input, length, output, outlen, options, last_chunk_options, decode_up_to_bad_char)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary_details(_ input: UnsafePointer<CChar>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options) -> simdutf_full_result {
  CSimdUTF.simdutf_base64_to_binary_details(input, length, output, options, last_chunk_options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_to_binary_details_utf16(_ input: UnsafePointer<UInt16>?, _ length: Int, _ output: UnsafeMutablePointer<CChar>?, _ options: simdutf_base64_options, _ last_chunk_options: simdutf_last_chunk_handling_options) -> simdutf_full_result {
  CSimdUTF.simdutf_base64_to_binary_details_utf16(input, length, output, options, last_chunk_options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_valid(_ input: CChar, _ options: simdutf_base64_options) -> Bool {
  CSimdUTF.simdutf_base64_valid(input, options)
}
#endif

#if (Base64)
@inlinable
@inline(__always)
public func simdutf_base64_valid_utf16(_ input: UInt16, _ options: simdutf_base64_options) -> Bool {
  CSimdUTF.simdutf_base64_valid_utf16(input, options)
}
#endif
