// Generated by Scripts/generate-bindings.py. Do not edit directly.
// Adapted from simdutf, available under MIT or Apache-2.0.
// See simdutf/LICENSE-MIT and simdutf/LICENSE-APACHE.
#include "SimdUTFConfig.h"
#include "CSimdUTF.h"
#include <simdutf.h>
static_assert(sizeof(uint16_t) == sizeof(char16_t));
static_assert(alignof(uint16_t) == alignof(char16_t));
static_assert(sizeof(uint32_t) == sizeof(char32_t));
static_assert(alignof(uint32_t) == alignof(char32_t));

static simdutf_result to_c_result(const simdutf::result &r) {
  return {static_cast<simdutf_error_code>(r.error), r.count};
}

static simdutf_full_result to_c_full_result(const simdutf::full_result &r) {
  return {static_cast<simdutf_error_code>(r.error), r.input_count, r.output_count};
}

extern "C" {

#if (SIMDUTF_FEATURE_UTF8 || SIMDUTF_FEATURE_DETECT_ENCODING)
bool simdutf_validate_utf8(const char *buf, size_t len) {
  return simdutf::validate_utf8(buf, len);
}
#endif

#if (SIMDUTF_FEATURE_UTF8)
simdutf_result simdutf_validate_utf8_with_errors(const char *buf, size_t len) {
  return to_c_result(simdutf::validate_utf8_with_errors(buf, len));
}
#endif

#if (SIMDUTF_FEATURE_DETECT_ENCODING)
simdutf_encoding_type simdutf_autodetect_encoding(const char *input,
                                                  size_t length) {
  return static_cast<simdutf_encoding_type>(
      simdutf::autodetect_encoding(input, length));
}
#endif

#if (SIMDUTF_FEATURE_DETECT_ENCODING)
int simdutf_detect_encodings(const char *input, size_t length) {
  return simdutf::detect_encodings(input, length);
}
#endif

#if (SIMDUTF_FEATURE_ASCII)
bool simdutf_validate_ascii(const char *buf, size_t len) {
  return simdutf::validate_ascii(buf, len);
}
#endif

#if (SIMDUTF_FEATURE_ASCII)
simdutf_result simdutf_validate_ascii_with_errors(const char *buf, size_t len) {
  return to_c_result(simdutf::validate_ascii_with_errors(buf, len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_ASCII)
bool simdutf_validate_utf16_as_ascii(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16_as_ascii(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_ASCII)
bool simdutf_validate_utf16be_as_ascii(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16be_as_ascii(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_ASCII)
bool simdutf_validate_utf16le_as_ascii(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16le_as_ascii(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
bool simdutf_validate_utf16(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 || SIMDUTF_FEATURE_DETECT_ENCODING)
bool simdutf_validate_utf16le(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16le(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
bool simdutf_validate_utf16be(const uint16_t *buf, size_t len) {
  return simdutf::validate_utf16be(reinterpret_cast<const char16_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_validate_utf16_with_errors(const uint16_t *buf,
                                                  size_t len) {
  return to_c_result(simdutf::validate_utf16_with_errors(reinterpret_cast<const char16_t *>(buf), len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_validate_utf16le_with_errors(const uint16_t *buf,
                                                    size_t len) {
  return to_c_result(simdutf::validate_utf16le_with_errors(reinterpret_cast<const char16_t *>(buf), len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_validate_utf16be_with_errors(const uint16_t *buf,
                                                    size_t len) {
  return to_c_result(simdutf::validate_utf16be_with_errors(reinterpret_cast<const char16_t *>(buf), len));
}
#endif

#if (SIMDUTF_FEATURE_UTF32 || SIMDUTF_FEATURE_DETECT_ENCODING)
bool simdutf_validate_utf32(const uint32_t *buf, size_t len) {
  return simdutf::validate_utf32(reinterpret_cast<const char32_t *>(buf), len);
}
#endif

#if (SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_validate_utf32_with_errors(const uint32_t *buf,
                                                  size_t len) {
  return to_c_result(simdutf::validate_utf32_with_errors(reinterpret_cast<const char32_t *>(buf), len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
void simdutf_to_well_formed_utf16le(const uint16_t *input, size_t len,
                                    uint16_t *output) {
  simdutf::to_well_formed_utf16le(reinterpret_cast<const char16_t *>(input), len, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
void simdutf_to_well_formed_utf16be(const uint16_t *input, size_t len,
                                    uint16_t *output) {
  simdutf::to_well_formed_utf16be(reinterpret_cast<const char16_t *>(input), len, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
void simdutf_to_well_formed_utf16(const uint16_t *input, size_t len,
                                  uint16_t *output) {
  simdutf::to_well_formed_utf16(reinterpret_cast<const char16_t *>(input), len, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
size_t simdutf_count_utf16(const uint16_t *input, size_t length) {
  return simdutf::count_utf16(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
size_t simdutf_count_utf16le(const uint16_t *input, size_t length) {
  return simdutf::count_utf16le(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF16)
size_t simdutf_count_utf16be(const uint16_t *input, size_t length) {
  return simdutf::count_utf16be(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8)
size_t simdutf_count_utf8(const char *input, size_t length) {
  return simdutf::count_utf8(input, length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_utf8_length_from_latin1(const char *input, size_t length) {
  return simdutf::utf8_length_from_latin1(input, length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_latin1_length_from_utf8(const char *input, size_t length) {
  return simdutf::latin1_length_from_utf8(input, length);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_latin1_length_from_utf16(size_t length) {
  return simdutf::latin1_length_from_utf16(length);
}
#endif

#if (SIMDUTF_FEATURE_UTF32 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_latin1_length_from_utf32(size_t length) {
  return simdutf::latin1_length_from_utf32(length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_utf16_length_from_utf8(const char *input, size_t length) {
  return simdutf::utf16_length_from_utf8(input, length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_utf32_length_from_utf8(const char *input, size_t length) {
  return simdutf::utf32_length_from_utf8(input, length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_utf8_length_from_utf16(const uint16_t *input, size_t length) {
  return simdutf::utf8_length_from_utf16(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_utf8_length_from_utf32(const uint32_t *input, size_t length) {
  return simdutf::utf8_length_from_utf32(reinterpret_cast<const char32_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_utf8_length_from_utf16_with_replacement(const uint16_t *input,
                                                size_t length) {
  return to_c_result(
      simdutf::utf8_length_from_utf16_with_replacement(reinterpret_cast<const char16_t *>(input), length));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_utf8_length_from_utf16le(const uint16_t *input, size_t length) {
  return simdutf::utf8_length_from_utf16le(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_utf8_length_from_utf16be(const uint16_t *input, size_t length) {
  return simdutf::utf8_length_from_utf16be(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_utf8_length_from_utf16le_with_replacement(const uint16_t *input,
                                                  size_t length) {
  return to_c_result(
      simdutf::utf8_length_from_utf16le_with_replacement(reinterpret_cast<const char16_t *>(input), length));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_utf8_length_from_utf16be_with_replacement(const uint16_t *input,
                                                  size_t length) {
  return to_c_result(
      simdutf::utf8_length_from_utf16be_with_replacement(reinterpret_cast<const char16_t *>(input), length));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf8(const char *input, size_t length,
                                      char *output) {
  return simdutf::convert_latin1_to_utf8(input, length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf8_safe(const char *input, size_t length,
                                           char *output, size_t utf8_len) {
  return simdutf::convert_latin1_to_utf8_safe(input, length, output, utf8_len);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
simdutf_full_result simdutf_convert_latin1_to_utf8_safe_with_details(
    const char *input, size_t length, char *output, size_t utf8_len) {
  return to_c_full_result(simdutf::convert_latin1_to_utf8_safe_with_details(
      input, length, output, utf8_len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf16le(const char *input, size_t length,
                                         uint16_t *output) {
  return simdutf::convert_latin1_to_utf16le(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf16be(const char *input, size_t length,
                                         uint16_t *output) {
  return simdutf::convert_latin1_to_utf16be(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf16(const char *input, size_t length,
                                       uint16_t *output) {
  return simdutf::convert_latin1_to_utf16(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF32 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_latin1_to_utf32(const char *input, size_t length,
                                       uint32_t *output) {
  return simdutf::convert_latin1_to_utf32(input, length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_utf8_to_latin1(const char *input, size_t length,
                                      char *output) {
  return simdutf::convert_utf8_to_latin1(input, length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf8_to_utf16le(const char *input, size_t length,
                                       uint16_t *output) {
  return simdutf::convert_utf8_to_utf16le(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf8_to_utf16(const char *input, size_t length,
                                     uint16_t *output) {
  return simdutf::convert_utf8_to_utf16(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf8_to_utf16be(const char *input, size_t length,
                                       uint16_t *output) {
  return simdutf::convert_utf8_to_utf16be(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf8_to_utf32(const char *input, size_t length,
                                     uint32_t *output) {
  return simdutf::convert_utf8_to_utf32(input, length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
simdutf_result simdutf_convert_utf8_to_latin1_with_errors(const char *input,
                                                          size_t length,
                                                          char *output) {
  return to_c_result(
      simdutf::convert_utf8_to_latin1_with_errors(input, length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf8_to_utf16_with_errors(const char *input,
                                                         size_t length,
                                                         uint16_t *output) {
  return to_c_result(
      simdutf::convert_utf8_to_utf16_with_errors(input, length, reinterpret_cast<char16_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf8_to_utf16le_with_errors(const char *input,
                                                           size_t length,
                                                           uint16_t *output) {
  return to_c_result(
      simdutf::convert_utf8_to_utf16le_with_errors(input, length, reinterpret_cast<char16_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf8_to_utf16be_with_errors(const char *input,
                                                           size_t length,
                                                           uint16_t *output) {
  return to_c_result(
      simdutf::convert_utf8_to_utf16be_with_errors(input, length, reinterpret_cast<char16_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_convert_utf8_to_utf32_with_errors(const char *input,
                                                         size_t length,
                                                         uint32_t *output) {
  return to_c_result(
      simdutf::convert_utf8_to_utf32_with_errors(input, length, reinterpret_cast<char32_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_valid_utf8_to_latin1(const char *input, size_t length,
                                            char *output) {
  return simdutf::convert_valid_utf8_to_latin1(input, length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_valid_utf8_to_utf16le(const char *input, size_t length,
                                             uint16_t *output) {
  return simdutf::convert_valid_utf8_to_utf16le(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_valid_utf8_to_utf16be(const char *input, size_t length,
                                             uint16_t *output) {
  return simdutf::convert_valid_utf8_to_utf16be(input, length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_valid_utf8_to_utf32(const char *input, size_t length,
                                           uint32_t *output) {
  return simdutf::convert_valid_utf8_to_utf32(input, length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16_to_utf8(const uint16_t *input, size_t length,
                                     char *output) {
  return simdutf::convert_utf16_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16_to_utf8_safe(const uint16_t *input, size_t length,
                                          char *output, size_t utf8_len) {
  return simdutf::convert_utf16_to_utf8_safe(reinterpret_cast<const char16_t *>(input), length, output, utf8_len);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_full_result simdutf_convert_utf16_to_utf8_safe_with_details(
    const uint16_t *input, size_t length, char *output, size_t utf8_len) {
  return to_c_full_result(simdutf::convert_utf16_to_utf8_safe_with_details(
      reinterpret_cast<const char16_t *>(input), length, output, utf8_len));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_utf16_to_latin1(const uint16_t *input, size_t length,
                                       char *output) {
  return simdutf::convert_utf16_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_utf16le_to_latin1(const uint16_t *input, size_t length,
                                         char *output) {
  return simdutf::convert_utf16le_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_utf16be_to_latin1(const uint16_t *input, size_t length,
                                         char *output) {
  return simdutf::convert_utf16be_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
simdutf_result simdutf_convert_utf16_to_latin1_with_errors(const uint16_t *input,
                                            size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf16_to_latin1_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
simdutf_result simdutf_convert_utf16le_to_latin1_with_errors(const uint16_t *input,
                                              size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf16le_to_latin1_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
simdutf_result simdutf_convert_utf16be_to_latin1_with_errors(const uint16_t *input,
                                              size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf16be_to_latin1_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf16_to_utf8_with_errors(const uint16_t *input,
                                                         size_t length,
                                                         char *output) {
  return to_c_result(
      simdutf::convert_utf16_to_utf8_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf16le_to_utf8_with_errors(const uint16_t *input,
                                            size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf16le_to_utf8_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_result simdutf_convert_utf16be_to_utf8_with_errors(const uint16_t *input,
                                            size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf16be_to_utf8_with_errors(reinterpret_cast<const char16_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16le_to_utf8(const uint16_t *input, size_t length,
                                       char *output) {
  return simdutf::convert_utf16le_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16be_to_utf8(const uint16_t *input, size_t length,
                                       char *output) {
  return simdutf::convert_utf16be_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16_to_utf8_with_replacement(const uint16_t *input,
                                                      size_t length,
                                                      char *output) {
  return simdutf::convert_utf16_to_utf8_with_replacement(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
simdutf_full_result simdutf_convert_utf16_to_utf8_with_replacement_safe(
    const uint16_t *input, size_t length, char *output, size_t utf8_len) {
  return to_c_full_result(simdutf::convert_utf16_to_utf8_with_replacement_safe(
      reinterpret_cast<const char16_t *>(input), length, output, utf8_len));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16le_to_utf8_with_replacement(const uint16_t *input,
                                                        size_t length,
                                                        char *output) {
  return simdutf::convert_utf16le_to_utf8_with_replacement(reinterpret_cast<const char16_t *>(input), length,
                                                           output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_utf16be_to_utf8_with_replacement(const uint16_t *input,
                                                        size_t length,
                                                        char *output) {
  return simdutf::convert_utf16be_to_utf8_with_replacement(reinterpret_cast<const char16_t *>(input), length,
                                                           output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_valid_utf16_to_utf8(const uint16_t *input, size_t length,
                                           char *output) {
  return simdutf::convert_valid_utf16_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_valid_utf16_to_latin1(const uint16_t *input,
                                             size_t length, char *output) {
  return simdutf::convert_valid_utf16_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_valid_utf16le_to_latin1(const uint16_t *input,
                                               size_t length, char *output) {
  return simdutf::convert_valid_utf16le_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_LATIN1)
size_t simdutf_convert_valid_utf16be_to_latin1(const uint16_t *input,
                                               size_t length, char *output) {
  return simdutf::convert_valid_utf16be_to_latin1(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_valid_utf16le_to_utf8(const uint16_t *input,
                                             size_t length, char *output) {
  return simdutf::convert_valid_utf16le_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF16)
size_t simdutf_convert_valid_utf16be_to_utf8(const uint16_t *input,
                                             size_t length, char *output) {
  return simdutf::convert_valid_utf16be_to_utf8(reinterpret_cast<const char16_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf16_to_utf32(const uint16_t *input, size_t length,
                                      uint32_t *output) {
  return simdutf::convert_utf16_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf16le_to_utf32(const uint16_t *input, size_t length,
                                        uint32_t *output) {
  return simdutf::convert_utf16le_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf16be_to_utf32(const uint16_t *input, size_t length,
                                        uint32_t *output) {
  return simdutf::convert_utf16be_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_convert_utf16_to_utf32_with_errors(const uint16_t *input,
                                                          size_t length,
                                                          uint32_t *output) {
  return to_c_result(
      simdutf::convert_utf16_to_utf32_with_errors(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_convert_utf16le_to_utf32_with_errors(const uint16_t *input,
                                             size_t length, uint32_t *output) {
  return to_c_result(
      simdutf::convert_utf16le_to_utf32_with_errors(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_convert_utf16be_to_utf32_with_errors(const uint16_t *input,
                                             size_t length, uint32_t *output) {
  return to_c_result(
      simdutf::convert_utf16be_to_utf32_with_errors(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output)));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_valid_utf16_to_utf32(const uint16_t *input,
                                            size_t length, uint32_t *output) {
  return simdutf::convert_valid_utf16_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_valid_utf16le_to_utf32(const uint16_t *input,
                                              size_t length, uint32_t *output) {
  return simdutf::convert_valid_utf16le_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_valid_utf16be_to_utf32(const uint16_t *input,
                                              size_t length, uint32_t *output) {
  return simdutf::convert_valid_utf16be_to_utf32(reinterpret_cast<const char16_t *>(input), length, reinterpret_cast<char32_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf32_to_utf8(const uint32_t *input, size_t length,
                                     char *output) {
  return simdutf::convert_utf32_to_utf8(reinterpret_cast<const char32_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
simdutf_result simdutf_convert_utf32_to_utf8_with_errors(const uint32_t *input,
                                                         size_t length,
                                                         char *output) {
  return to_c_result(
      simdutf::convert_utf32_to_utf8_with_errors(reinterpret_cast<const char32_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_UTF8 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_valid_utf32_to_utf8(const uint32_t *input, size_t length,
                                           char *output) {
  return simdutf::convert_valid_utf32_to_utf8(reinterpret_cast<const char32_t *>(input), length, output);
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf32_to_utf16(const uint32_t *input, size_t length,
                                      uint16_t *output) {
  return simdutf::convert_utf32_to_utf16(reinterpret_cast<const char32_t *>(input), length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf32_to_utf16le(const uint32_t *input, size_t length,
                                        uint16_t *output) {
  return simdutf::convert_utf32_to_utf16le(reinterpret_cast<const char32_t *>(input), length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF16 && SIMDUTF_FEATURE_UTF32)
size_t simdutf_convert_utf32_to_utf16be(const uint32_t *input, size_t length,
                                        uint16_t *output) {
  return simdutf::convert_utf32_to_utf16be(reinterpret_cast<const char32_t *>(input), length, reinterpret_cast<char16_t *>(output));
}
#endif

#if (SIMDUTF_FEATURE_UTF32 && SIMDUTF_FEATURE_LATIN1)
simdutf_result simdutf_convert_utf32_to_latin1_with_errors(const uint32_t *input,
                                            size_t length, char *output) {
  return to_c_result(
      simdutf::convert_utf32_to_latin1_with_errors(reinterpret_cast<const char32_t *>(input), length, output));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
const char * simdutf_find(const char *start, const char *end, char character) {
  return simdutf::find(start, end, character);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
const uint16_t * simdutf_find_utf16(const uint16_t *start, const uint16_t *end,
                                   uint16_t character) {
  return reinterpret_cast<const uint16_t *>(simdutf::find(reinterpret_cast<const char16_t *>(start), reinterpret_cast<const char16_t *>(end), static_cast<char16_t>(character)));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_maximal_binary_length_from_base64(const char *input,
                                                 size_t length) {
  return simdutf::maximal_binary_length_from_base64(input, length);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_maximal_binary_length_from_base64_utf16(const uint16_t *input,
                                                       size_t length) {
  return simdutf::maximal_binary_length_from_base64(reinterpret_cast<const char16_t *>(input), length);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_result simdutf_base64_to_binary(
    const char *input, size_t length, char *output,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options) {
  return to_c_result(simdutf::base64_to_binary(
      input, length, output, static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options)));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_result simdutf_base64_to_binary_utf16(
    const uint16_t *input, size_t length, char *output,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options) {
  return to_c_result(simdutf::base64_to_binary(
      reinterpret_cast<const char16_t *>(input), length, output, static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options)));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_base64_length_from_binary(size_t length,
                                         simdutf_base64_options options) {
  return simdutf::base64_length_from_binary(
      length, static_cast<simdutf::base64_options>(options));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_base64_length_from_binary_with_lines(
    size_t length, simdutf_base64_options options, size_t line_length) {
  return simdutf::base64_length_from_binary_with_lines(
      length, static_cast<simdutf::base64_options>(options), line_length);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_binary_to_base64(const char *input, size_t length, char *output,
                                simdutf_base64_options options) {
  return simdutf::binary_to_base64(
      input, length, output, static_cast<simdutf::base64_options>(options));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
size_t simdutf_binary_to_base64_with_lines(const char *input, size_t length,
                                           char *output, size_t line_length,
                                           simdutf_base64_options options) {
  return simdutf::binary_to_base64_with_lines(
      input, length, output, line_length,
      static_cast<simdutf::base64_options>(options));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_result simdutf_base64_to_binary_safe(
    const char *input, size_t length, char *output, size_t *outlen,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options,
    bool decode_up_to_bad_char) {
  size_t local_out = outlen ? *outlen : 0;
  simdutf::result r = simdutf::base64_to_binary_safe(
      input, length, output, local_out,
      static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options),
      decode_up_to_bad_char);
  if (outlen)
    *outlen = local_out;
  return to_c_result(r);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_result simdutf_base64_to_binary_safe_utf16(
    const uint16_t *input, size_t length, char *output, size_t *outlen,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options,
    bool decode_up_to_bad_char) {
  size_t local_out = outlen ? *outlen : 0;
  simdutf::result r = simdutf::base64_to_binary_safe(
      reinterpret_cast<const char16_t *>(input), length, output, local_out,
      static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options),
      decode_up_to_bad_char);
  if (outlen)
    *outlen = local_out;
  return to_c_result(r);
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_full_result simdutf_base64_to_binary_details(
    const char *input, size_t length, char *output,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options) {
  return to_c_full_result(simdutf::base64_to_binary_details(
      input, length, output, static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options)));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
simdutf_full_result simdutf_base64_to_binary_details_utf16(
    const uint16_t *input, size_t length, char *output,
    simdutf_base64_options options,
    simdutf_last_chunk_handling_options last_chunk_options) {
  return to_c_full_result(simdutf::base64_to_binary_details(
      reinterpret_cast<const char16_t *>(input), length, output, static_cast<simdutf::base64_options>(options),
      static_cast<simdutf::last_chunk_handling_options>(last_chunk_options)));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
bool simdutf_base64_valid(char input, simdutf_base64_options options) {
  return simdutf::base64_valid(input,
                               static_cast<simdutf::base64_options>(options));
}
#endif

#if (SIMDUTF_FEATURE_BASE64)
bool simdutf_base64_valid_utf16(uint16_t input,
                                simdutf_base64_options options) {
  return simdutf::base64_valid(static_cast<char16_t>(input),
                               static_cast<simdutf::base64_options>(options));
}
#endif

} // extern "C"
