#!/usr/bin/env python3
"""Regenerate checked-in C and Swift bindings from the pinned simdutf submodule.

The upstream C API is all-or-nothing. This adapter uses the feature conditions
of its C++ callees so each SwiftPM trait can compile independently. No upstream
files are modified. Review generated changes when updating the submodule.
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "simdutf"
C_TARGET = ROOT / "Sources" / "CSimdUTF"
SWIFT_TARGET = ROOT / "Sources" / "SimdUTF"
FEATURE_TRAITS = {
    "UTF8": "UTF8",
    "UTF16": "UTF16",
    "UTF32": "UTF32",
    "ASCII": "ASCII",
    "LATIN1": "Latin1",
    "BASE64": "Base64",
    "DETECT_ENCODING": "DetectEncoding",
}
NOTICE = """// Generated by Scripts/generate-bindings.py. Do not edit directly.
// Adapted from simdutf, available under MIT or Apache-2.0.
// See simdutf/LICENSE-MIT and simdutf/LICENSE-APACHE.
"""


def strip_comments(source: str) -> str:
    # Preserve line positions for feature-condition lookup.
    return re.sub(r"/\*.*?\*/|//[^\n]*", lambda m: re.sub(r"[^\n]", " ", m[0]), source, flags=re.S)


def conditions_by_line(source: str) -> list[str]:
    """Track upstream #if feature expressions, ignoring unrelated guards."""
    conditions = []
    stack = []
    continued = ""
    for line in strip_comments(source).splitlines():
        current = line.strip()
        if continued:
            current = continued + current
        if current.endswith("\\"):
            continued = current[:-1] + " "
            conditions.append(" && ".join(f"({value})" for value in stack if value))
            continue
        continued = ""
        if re.match(r"#\s*(if|ifdef|ifndef)\b", current):
            expression = re.sub(r"^#\s*(if|ifdef|ifndef)\s+", "", current)
            stack.append(expression if "SIMDUTF_FEATURE_" in expression else None)
        elif re.match(r"#\s*endif\b", current):
            stack.pop()
        elif re.match(r"#\s*else\b", current):
            if stack[-1]:
                stack[-1] = f"!({stack[-1]})"
        elif re.match(r"#\s*elif\b", current):
            raise ValueError("Handle upstream #elif explicitly before regenerating bindings")
        conditions.append(" && ".join(f"({value})" for value in stack if value))
    return conditions


def upstream_condition(name: str, implementation: str, conditions: list[str], parameters: str) -> str:
    # Some C wrappers add _utf16 to distinguish overloads.
    cpp_name = name.removeprefix("simdutf_")
    code = strip_comments(implementation)
    for candidate in (cpp_name, cpp_name.removesuffix("_utf16")):
        for match in re.finditer(rf"\b{candidate}\s*\(([^()]*)\)\s*(?:noexcept|[;{{])", code):
            # Match the C++ character-width overload rather than selecting its
            # first occurrence. Calls and std::span overloads are excluded.
            if any((width in parameters) != (width in match[1]) for width in ("char16_t", "char32_t")):
                continue
            if "std::span" in match[1]:
                continue
            line = implementation[:match.start()].count("\n")
            condition = conditions[line]
            if condition:
                return condition
    raise ValueError(f"No upstream feature condition found for {name} ({cpp_name})")


def swift_condition(condition: str) -> str:
    for macro, trait in FEATURE_TRAITS.items():
        condition = condition.replace("SIMDUTF_FEATURE_" + macro, trait)
    return condition


def c_type(source: str) -> str:
    return source.replace("char16_t", "uint16_t").replace("char32_t", "uint32_t")


def swift_type(source: str) -> str:
    source = " ".join(source.split())
    pointer = "*" in source
    mutable = not source.startswith("const ")
    base = source.replace("const ", "").replace("*", "").strip()
    base = {
        "char": "CChar",
        "uint8_t": "UInt8",
        "uint16_t": "UInt16",
        "uint32_t": "UInt32",
        "size_t": "Int",
        "int": "Int32",
        "bool": "Bool",
        "void": "Void",
    }.get(base, base)
    if pointer:
        return f"Unsafe{'Mutable' if mutable else ''}Pointer<{base}>?"
    return base


def parse_parameters(source: str) -> list[tuple[str, str]]:
    parameters = []
    for parameter in source.split(","):
        match = re.fullmatch(r"\s*(.*?)\b(\w+)\s*", parameter)
        if not match:
            raise ValueError(f"Unsupported parameter: {parameter}")
        parameters.append((" ".join(match[1].split()), match[2]))
    return parameters


def swift_function(result: str, name: str, parameters: list[tuple[str, str]], condition: str) -> str:
    declarations = ", ".join(f"_ {name}: {swift_type(type)}" for type, name in parameters)
    arguments = ", ".join(name for _, name in parameters)
    result = swift_type(result)
    return f"""#if {swift_condition(condition)}
@inlinable
@inline(__always)
public func {name}({declarations}) -> {result} {{
  CSimdUTF.{name}({arguments})
}}
#endif
"""


def main() -> None:
    C_TARGET.mkdir(parents=True, exist_ok=True)
    (C_TARGET / "include").mkdir(exist_ok=True)
    SWIFT_TARGET.mkdir(parents=True, exist_ok=True)

    header = (UPSTREAM / "include" / "simdutf_c.h").read_text()
    # Use explicit C integer types. Importing char16_t aliases from uchar.h can
    # produce incompatible Swift types between host platforms.
    header = re.sub(r"#ifdef __has_include.*?#endif // __has_include\n", "", header, flags=re.S)
    header = c_type(header).replace("SIMDUTF_C_H", "SIMDUTF_SWIFT_C_API_H")
    header = header.replace(
        "#endif /* SIMDUTF_SWIFT_C_API_H */",
        '#include "SimdUTFBridge.h"\n\n#endif /* SIMDUTF_SWIFT_C_API_H */',
    )
    (C_TARGET / "include" / "CSimdUTF.h").write_text(NOTICE + header)

    # The upstream entry point includes an all-features-only C wrapper. Omit
    # that include because the package supplies individually gated wrappers.
    implementation = (UPSTREAM / "src" / "simdutf.cpp").read_text()
    implementation = implementation.replace('#include "simdutf_c.cpp"\n', "")
    implementation = re.sub(
        r'#include "([^"]+)"',
        lambda match: '#include "../../simdutf/src/' + match[1] + '"'
        if (UPSTREAM / "src" / match[1]).is_file() else match[0],
        implementation,
    )
    (C_TARGET / "SimdUTFImplementation.cpp").write_text(
        NOTICE + '#include "SimdUTFConfig.h"\n\n' + implementation
    )

    cpp_header = (UPSTREAM / "include" / "simdutf" / "implementation.h").read_text()
    cpp_conditions = conditions_by_line(cpp_header)
    original = (UPSTREAM / "src" / "simdutf_c.cpp").read_text()
    pattern = re.compile(
        r"^(void|bool|int|size_t|simdutf_result|simdutf_full_result|simdutf_encoding_type|const char\s*\*|const char16_t\s*\*)\s*"
        r"(simdutf_\w+)\s*\((.*?)\)\s*\{(.*?)\n\}", re.M | re.S
    )
    functions = list(pattern.finditer(original))
    declarations = re.findall(r"\b(simdutf_\w+)\s*\([^;{}]*\)\s*;", strip_comments(header))
    assert set(declarations) == {match[2] for match in functions}, "C header and implementation API differ"

    cpp = [NOTICE, '#include "SimdUTFConfig.h"\n#include "CSimdUTF.h"\n#include <simdutf.h>\n',
           "static_assert(sizeof(uint16_t) == sizeof(char16_t));\n"
           "static_assert(alignof(uint16_t) == alignof(char16_t));\n"
           "static_assert(sizeof(uint32_t) == sizeof(char32_t));\n"
           "static_assert(alignof(uint32_t) == alignof(char32_t));\n\n",
           "static simdutf_result to_c_result(const simdutf::result &r) {\n"
           "  return {static_cast<simdutf_error_code>(r.error), r.count};\n}\n\n"
           "static simdutf_full_result to_c_full_result(const simdutf::full_result &r) {\n"
           "  return {static_cast<simdutf_error_code>(r.error), r.input_count, r.output_count};\n}\n\n",
           'extern "C" {\n\n']
    swift = [NOTICE, "import CSimdUTF\n\n",
             "// C result types are values; buffers stay borrowed for the duration of each call.\n"]
    for name in ("simdutf_error_code", "simdutf_result", "simdutf_full_result"):
        swift.append(f"public typealias {name} = CSimdUTF.{name}\n")
    for constant in re.findall(r"\b(SIMDUTF_ERROR_\w+)\s*=|\b(SIMDUTF_ERROR_\w+)\s*[,\n]", header):
        name = next(value for value in constant if value)
        swift.append(f"public let {name} = CSimdUTF.{name}\n")
    for trait, aliases, prefix in (
        ("DetectEncoding", ["simdutf_encoding_type"], "SIMDUTF_ENCODING_"),
        ("Base64", ["simdutf_base64_options", "simdutf_last_chunk_handling_options"], "SIMDUTF_(?:BASE64|LAST_CHUNK)_"),
    ):
        swift.append(f"\n#if {trait}\n")
        for name in aliases:
            swift.append(f"public typealias {name} = CSimdUTF.{name}\n")
        for name in re.findall(rf"\b({prefix}\w+)\s*=", header):
            swift.append(f"public let {name} = CSimdUTF.{name}\n")
        swift.append("#endif\n")
    swift.append("\n// The counted-buffer APIs follow the upstream C API. Counts and capacities\n"
                 "// must be nonnegative. Conversion inputs and\n"
                 "// outputs must not overlap. Supply enough output capacity as documented by\n"
                 "// simdutf; *_safe variants accept explicit output capacity.\n\n")

    for match in functions:
        result, name, raw_parameters, body = match.groups()
        parameters = parse_parameters(raw_parameters)
        condition = upstream_condition(name, cpp_header, cpp_conditions, raw_parameters)
        signature = c_type(result) + " " + name + "(" + c_type(raw_parameters) + ")"
        for parameter_type, parameter_name in parameters:
            if "char16_t" in parameter_type or "char32_t" in parameter_type:
                if "*" in parameter_type:
                    replacement = f"reinterpret_cast<{parameter_type}>({parameter_name})"
                else:
                    replacement = f"static_cast<{parameter_type}>({parameter_name})"
                body = re.sub(rf"\b{parameter_name}\b", replacement, body)
        if "*" in result and "char16_t" in result:
            body = re.sub(r"return\s+(.*?);", lambda m: f"return reinterpret_cast<{c_type(result)}>({m[1]});", body, flags=re.S)
        cpp.append(f"#if {condition}\n{signature} {{{body}\n}}\n#endif\n\n")
        swift.append(swift_function(c_type(result), name, [(c_type(t), n) for t, n in parameters], condition) + "\n")

    cpp.append('} // extern "C"\n')
    (C_TARGET / "SimdUTFCAPI.cpp").write_text("".join(cpp))
    (SWIFT_TARGET / "SimdUTF.swift").write_text("".join(swift).rstrip() + "\n")
    print(f"Generated {len(functions)} individually gated C and Swift functions")


if __name__ == "__main__":
    main()
